// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8vKiPtF5Ea5kGsASMBTtG5XofZ3KlYgs',
    appId: '1:918277831940:web:f5e4d45c0da7e150b9e451',
    messagingSenderId: '918277831940',
    projectId: 'ui-radar',
    authDomain: 'ui-radar.firebaseapp.com',
    storageBucket: 'ui-radar.firebasestorage.app',
    measurementId: 'G-BG4CM7673J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAercXcIYEV1rv5jXIX8HDNPtuyhb7D7yU',
    appId: '1:918277831940:android:f59c79a6d8ed2d7db9e451',
    messagingSenderId: '918277831940',
    projectId: 'ui-radar',
    storageBucket: 'ui-radar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7P74g_rCbS6pLKf1IOdMAeaMmMvELH08',
    appId: '1:918277831940:ios:3d2d1342d341b7f0b9e451',
    messagingSenderId: '918277831940',
    projectId: 'ui-radar',
    storageBucket: 'ui-radar.firebasestorage.app',
    iosBundleId: 'com.example.researchMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7P74g_rCbS6pLKf1IOdMAeaMmMvELH08',
    appId: '1:918277831940:ios:3d2d1342d341b7f0b9e451',
    messagingSenderId: '918277831940',
    projectId: 'ui-radar',
    storageBucket: 'ui-radar.firebasestorage.app',
    iosBundleId: 'com.example.researchMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8vKiPtF5Ea5kGsASMBTtG5XofZ3KlYgs',
    appId: '1:918277831940:web:bea2b45f34a31ed4b9e451',
    messagingSenderId: '918277831940',
    projectId: 'ui-radar',
    authDomain: 'ui-radar.firebaseapp.com',
    storageBucket: 'ui-radar.firebasestorage.app',
    measurementId: 'G-LYXRBNWS93',
  );
}
